Create ContactService
Vershinin-V-V/learning240221 pull request #3
Opened 2021-03-21 18:02 UTC by Vershinin-V-V

Добавил сервис ContactService с методами для получения списка контактов и конкретного контакта по id из ContactList.
Сервис запускается не в основном потоке...
Не работает! не могу найти ошибку. Дебажил код, сервис работает, находит контакт по id (val currentContact) в ContactDetailsFragment и ContactListFragment, но не заполняет значения вьюшек. Хотя может уже и сервис не работает, с тем количеством исправлений, которые я вносил и переписывал. Сейчас по крайней мере приложение не падает, от запроса методов сервиса, который не успевает инициализировался. Я уже глубоко запутался, подскажите, пожалуйста, с какого места начать выпутываться, или вообще всё откатить к предыдущему коммиту, и писать заново.

2021-03-21 18:16 UTC, murrcha commented
> Добавил сервис ContactService с методами для получения списка контактов и конкретного контакта по id из ContactList.
> Сервис запускается не в основном потоке...
> Не работает! не могу найти ошибку. Дебажил код, сервис работает, находит контакт по id (val currentContact) в ContactDetailsFragment и ContactListFragment, но не заполняет значения вьюшек. Хотя может уже и сервис не работает, с тем количеством исправлений, которые я вносил и переписывал. Сейчас по крайней мере приложение не падает, от запроса методов сервиса, который не успевает инициализировался. Я уже глубоко запутался, подскажите, пожалуйста, с какого места начать выпутываться, или вообще всё откатить к предыдущему коммиту, и писать заново.

Предлагаю убрать корутины и сделать с использованием Thread

2021-03-21 18:19 UTC, murrcha commented on app/src/main/java/com/classic117/classicproject/ContactDetailsFragment.kt
> +                while (serviceBound()) {
Для чего while? Разве не достаточно сделать это 1 раз?

2021-03-21 18:20 UTC, murrcha commented on app/src/main/java/com/classic117/classicproject/ContactList.kt
> +//        Person(2,"Tom","1234289","444839203","tom1@mail.com","tom2@mail.com", "Это не Боб")
Закомментированный код нужно убрать

2021-03-21 18:21 UTC, murrcha commented on app/src/main/java/com/classic117/classicproject/ContactListFragment.kt
> +    private lateinit var coroutineScope: CoroutineScope
Попробуйте сделать без корутин

2021-03-21 18:21 UTC, murrcha commented on app/src/main/java/com/classic117/classicproject/ContactListFragment.kt
> +        coroutineScope = CoroutineScope(Dispatchers.IO)
это здесь лишнее

2021-03-21 18:23 UTC, murrcha commented on app/src/main/java/com/classic117/classicproject/ContactListFragment.kt
> +                        requireActivity().runOnUiThread {
Мешать корутины и хэндлер не стоит

2021-03-21 18:24 UTC, murrcha commented on app/src/main/java/com/classic117/classicproject/ContactListFragment.kt
> +                        println("ошибка лист")
Для логирования лучше использовать Log.e(e)

2021-03-21 18:25 UTC, murrcha commented on app/src/main/java/com/classic117/classicproject/MainActivity.kt
> +        if (!bound) {
для чего здесь условие?

2021-03-21 18:26 UTC, murrcha commented on app/src/main/java/com/classic117/classicproject/ContactDetailsFragment.kt
> +            coroutineScope = CoroutineScope(Dispatchers.IO)
это здесь лишнее

2021-03-21 18:27 UTC, murrcha commented on app/src/main/java/com/classic117/classicproject/ContactDetailsFragment.kt
> +                        println("ошибка детали")
Log.e(e)

2021-03-21 18:28 UTC, murrcha commented on app/src/main/java/com/classic117/classicproject/ContactDetailsFragment.kt
> +                putSerializable(ARG_PERSON_ID, contactId)
почему Int мы упаковываем в Serializable?

2021-03-21 18:30 UTC, murrcha commented on app/src/main/java/com/classic117/classicproject/ContactList.kt
> +        return contactList[contactId]
потенциальная ошибка может быть, к примеру, если попытаемся достать по индексу, которого нет

2021-03-21 18:31 UTC, murrcha commented on app/src/main/java/com/classic117/classicproject/ContactListFragment.kt
> +            serviceCallback = context}
Закрывающую скобку нужно перенести на новую строку, в студии есть горячие клавиши для форматирования `Alt + Ctrl + L`

2021-03-21 18:32 UTC, murrcha commented on app/src/main/java/com/classic117/classicproject/ContactListFragment.kt
> +                while (serviceBound()) {
while здесь не нужен

2021-03-21 18:33 UTC, murrcha commented on app/src/main/java/com/classic117/classicproject/ContactService.kt
> +    private lateinit var coroutineScope: CoroutineScope
Убираем все что связано с корутинами

2021-03-21 18:34 UTC, murrcha commented on app/src/main/java/com/classic117/classicproject/ContactService.kt
> +            withContext(coroutineScope.coroutineContext) {
Здесь вместо корутин используем Thread

2021-03-21 18:34 UTC, murrcha commented on app/src/main/java/com/classic117/classicproject/ContactService.kt
> +            withContext(coroutineScope.coroutineContext) {
Аналогично

2021-03-21 18:37 UTC, murrcha requested changes
В целом правильной дорогой идете, однако, у вас путаница с корутинами, поэтому лучше их убрать и сделать все на обычных Thread-ах, будет проще. Помните про работу сборщика мусора, что в Thread передавать ссылку на фрагмент просто так нельзя, иначе будет утечка, чтобы этого избежать нужно использовать специальный тип ссылок.

2021-03-23 12:20 UTC, Vershinin-V-V commented
Переписал. теперь всё работает

2021-03-23 15:47 UTC, murrcha commented on app/src/main/java/com/classic117/classicproject/ContactDetailsFragment.kt
> +                Log.e(TAG, e.stackTrace.toString())
Можно просто 
`Log.e(TAG, e.getMessage(), e)`
Либо проще подключить и использовать `Timber`

2021-03-29 18:06 UTC, merged