Create birthday notification
Vershinin-V-V/learning240221 pull request #4
Opened 2021-03-29 19:12 UTC by Vershinin-V-V

Изменил экран отображения деталей контакта
Добавил BirthdayReciver. 
Добавил напоминание о дне рождения контакта, в которое передается id и имя контакта через константы . Если ДР контакта 29 февраля, а год не високосный, то notification переноситься на 1-е марта.
При нажатии на уведомление открывается фрагмент "детали контакта".

2021-03-31 06:54 UTC, murrcha commented on app/src/main/java/com/classic117/classicproject/BirthdayReceiver.kt
> +    private var notificationManager: NotificationManager? = null
Данная переменная здесь не нужна, в методы передается context, из него можем получить данный manager в любое время

2021-03-31 06:57 UTC, murrcha commented on app/src/main/java/com/classic117/classicproject/BirthdayReceiver.kt
> +            return true
`return` в котлин можно вынести перед `if`

2021-03-31 06:59 UTC, murrcha commented on app/src/main/java/com/classic117/classicproject/BirthdayReceiver.kt
> +        if (alarmTime.get(Calendar.MONTH) == 1 && alarmTime.get(Calendar.DAY_OF_MONTH) == 29) {
Рекомендуется числа и строки выносить в говорящие константы, это упрощает чтение кода

2021-03-31 07:05 UTC, murrcha commented on app/src/main/java/com/classic117/classicproject/BirthdayReceiver.kt
> +            if (!isLeap(alarmTime.get(Calendar.YEAR))) {
Данное условие можно объединить с условием выше, это позволит избежать вложенности if-ов

2021-03-31 07:06 UTC, murrcha commented on app/src/main/java/com/classic117/classicproject/BirthdayReceiver.kt
> +        var alarmTime = Calendar.getInstance()
`var` здесь не нужен, достаточно `val`

2021-03-31 07:10 UTC, murrcha commented on app/src/main/java/com/classic117/classicproject/BirthdayReceiver.kt
> +        createNotificationChannel(context)
Желательно канал создать один раз, а не каждый раз при вызове onRecieve. Это можно сделать в activity.

2021-03-31 07:11 UTC, murrcha commented on app/src/main/java/com/classic117/classicproject/BirthdayReceiver.kt
> +    fun nextAlarmDate(): Calendar {
данный метод не используется во вне, нужно сделать его private

2021-03-31 08:38 UTC, murrcha commented on app/src/main/java/com/classic117/classicproject/BirthdayReceiver.kt
> +        if (alarmTime.get(Calendar.MONTH) == 1 && alarmTime.get(Calendar.DAY_OF_MONTH) == 29) {
да, рекомендуется явно задавать что значит то или иное число, чтобы не было "магических чисел"

2021-03-31 09:46 UTC, murrcha commented on app/src/main/java/com/classic117/classicproject/ContactDetailsFragment.kt
> +                getString(R.string.next_alarm) + " " + nextAlarmString,
аналогично

2021-03-31 12:16 UTC, Vershinin-V-V commented on app/src/main/java/com/classic117/classicproject/BirthdayReceiver.kt
> +import java.util.*
не нашел где отключается, но ничего кроме java.util не схлапывает

2021-03-31 12:17 UTC, Vershinin-V-V commented on app/src/main/java/com/classic117/classicproject/ContactDetailsFragment.kt
> +                .toString() + " " + nextAlarmDate().getDisplayName(
изменил на котлин стиль, остальные склейки вынес в ресурсы

2021-03-31 12:18 UTC, Vershinin-V-V commented
Исправил

2021-03-31 20:06 UTC, elestatte87 commented on app/src/main/AndroidManifest.xml
> +        <receiver
```suggestion
        <receiver android:name=".BirthdayReceiver" />
```

2021-03-31 20:07 UTC, elestatte87 commented on app/src/main/AndroidManifest.xml
> +            android:launchMode="singleTop">
Зачем вам это ?

2021-03-31 20:10 UTC, elestatte87 commented on app/src/main/java/com/classic117/classicproject/BirthdayReceiver.kt
> +    private var contactId: Int = 0
объявляйте лучше в теле onReceive в этом мало смысла

2021-03-31 20:11 UTC, elestatte87 commented on app/src/main/java/com/classic117/classicproject/BirthdayReceiver.kt
> +    private fun createNotification(context: Context, id: Int) {
showNotification

2021-03-31 20:11 UTC, elestatte87 commented on app/src/main/java/com/classic117/classicproject/BirthdayReceiver.kt
> +        val notificationIntent = Intent(context, MainActivity::class.java)
Intent - builder

2021-03-31 20:13 UTC, elestatte87 commented on app/src/main/java/com/classic117/classicproject/BirthdayReceiver.kt
> +        NotificationManagerCompat.from(context).run {
в run особого профита нет

2021-03-31 20:15 UTC, elestatte87 commented on app/src/main/java/com/classic117/classicproject/BirthdayReceiver.kt
> +    private fun isLeap(year: Int) = year % 400 == 0 || year % 100 != 0 && year % 4 == 0
year % 4 == 0 не достаточно ?

2021-03-31 20:16 UTC, elestatte87 commented on app/src/main/java/com/classic117/classicproject/BirthdayReceiver.kt
> +    private fun nextAlarmDate(): Calendar {
private fun nextAlarmDate() = Calendar.getInstance().apply {
    ...
}

2021-03-31 20:40 UTC, elestatte87 commented on app/src/main/AndroidManifest.xml
> +        <receiver
<receiver android:name=".BirthdayReceiver" />

2021-03-31 20:45 UTC, elestatte87 commented on app/src/main/java/com/classic117/classicproject/BirthdayReceiver.kt
> +        if (is29February(alarmTime) && !isLeap(alarmTime.get(Calendar.YEAR))) {
В этом 100% есть смысл. У меня не будет такого же поведения если я просто сделаю alarmTime.add(Calendar.YEAR, 1)
Извиняюсь тяжело в уме точно сообразить. Перепроверьте

2021-03-31 20:46 UTC, elestatte87 commented on app/src/main/java/com/classic117/classicproject/BirthdayReceiver.kt
> +            ?: throw IllegalArgumentException("Contact ID required")
Оставьте но проще было сделать ?: return
тут смысла особого нет крашить приложение

2021-03-31 20:48 UTC, elestatte87 commented on app/src/main/java/com/classic117/classicproject/ContactDetailsFragment.kt
> +const val ARG_PERSON_ID = "id"
разместите константы которые используются только в 1 месте там где они использованы и пометьте прайват

2021-03-31 20:49 UTC, elestatte87 commented on app/src/main/java/com/classic117/classicproject/ContactDetailsFragment.kt
> +    private lateinit var button: Button
есть биндинг к чему это ?

2021-03-31 20:49 UTC, elestatte87 commented on app/src/main/java/com/classic117/classicproject/ContactDetailsFragment.kt
> +    private var alarmOn: Boolean = false
private var alarmOn = false

2021-03-31 20:52 UTC, elestatte87 commented on app/src/main/java/com/classic117/classicproject/ContactDetailsFragment.kt
> +    private fun isLeap(year: Int) = year % 400 == 0 || year % 100 != 0 && year % 4 == 0
не соблюдается DRY принцип

2021-03-31 20:52 UTC, elestatte87 commented on app/src/main/java/com/classic117/classicproject/ContactDetailsFragment.kt
> +    private fun nextAlarmDate(): Calendar {
DRY

2021-03-31 20:55 UTC, elestatte87 commented on app/src/main/java/com/classic117/classicproject/ContactList.kt
> +        Calendar.getInstance().apply {
return Calendar.getInstance().apply {
            set(Calendar.DAY_OF_MONTH, day)
            set(Calendar.MONTH, month)
            set(Calendar.YEAR, year)
}

2021-03-31 20:56 UTC, elestatte87 commented on app/src/main/java/com/classic117/classicproject/ContactDetailsFragment.kt
> +    fun buttonFuction() {
нужна декомпозиция иливынос того что возможно в отдельный делегат класс

2021-03-31 20:57 UTC, elestatte87 commented on app/src/main/java/com/classic117/classicproject/ContactDetailsFragment.kt
> +                getString(R.string.birthday_date) + " " + contact.birthday.get(Calendar.DAY_OF_MONTH)
сделайте маску в ресурсах и подставляйте аргументы в нее

2021-03-31 21:00 UTC, elestatte87 commented on app/src/main/java/com/classic117/classicproject/MainActivity.kt
> +            val notificationManager: NotificationManager =
тип в котлине можно опускать

2021-03-31 21:03 UTC, elestatte87 commented on app/src/main/res/layout/contact_details_fragment.xml
> +        android:layout_width="match_parent"
почитайте гайды как лучше верстать ConstraintLayout
лучше заменить там где возможно на 0dp ширину или высоту

2021-04-01 05:03 UTC, Vershinin-V-V commented on app/src/main/java/com/classic117/classicproject/BirthdayReceiver.kt
> +    private fun isLeap(year: Int) = year % 400 == 0 || year % 100 != 0 && year % 4 == 0
нет, ведь есть шанс что приложение доживет до 2100-ого, а он не високосный)

2021-04-01 10:15 UTC, elestatte87 commented on app/src/main/java/com/classic117/classicproject/BirthdayReceiver.kt
> +    private fun isLeap(year: Int) = year % 400 == 0 || year % 100 != 0 && year % 4 == 0
Да все печально не только 2100
https://calculator888.ru/visokosnyy-god/

2021-04-01 12:55 UTC, Vershinin-V-V reviewed
Кроме замечаний про несоответствия DRY все переделал. Не могу придумать что делать с этими методами.

2021-04-01 13:19 UTC, Vershinin-V-V commented on app/src/main/java/com/classic117/classicproject/ContactDetailsFragment.kt
> +    private fun nextAlarmDate(): Calendar {
С этими дублируемыми методами не могу придумать, что сделать. Остальное переделал

2021-04-02 05:25 UTC, Vershinin-V-V commented on app/src/main/java/com/classic117/classicproject/BirthdayReceiver.kt
> +        if (is29February(alarmTime) && !isLeap(alarmTime.get(Calendar.YEAR))) {
Да, здесь точно есть смысл, но в изначальном моем варианте здесь как раз скрылся баг(на запуск эмулятора не хватает железа, а на физическом устройстве довольно неудобно экспериментировать с датой). действительно alarmTime.add(Calendar.YEAR, 1) сам  меняет дату с 29.02 на 1.03, но он же и не дает установить дату на 29.02. Изменил метод. теперь все работает корректно

2021-04-02 05:31 UTC, Vershinin-V-V commented on app/src/main/java/com/classic117/classicproject/ContactDetailsFragment.kt
> +    fun buttonFuction() {
вынес создание интента в метод, теперь на экран вмещается.

2021-04-05 11:03 UTC, thealbre commented on app/src/main/java/com/classic117/classicproject/BirthdayReceiver.kt
> +import java.util.*
Меняется в этих настройках. Не знаю, настроено ли у меня правильно, надо посмотреть, потыкать, попробовать)

![image](https://user-images.githubusercontent.com/27574322/113567613-fbf19c00-961f-11eb-9d77-5e60aaad000e.png)

2021-04-07 06:22 UTC, thealbre requested changes
Вообщем хороший ПР, но нужно поправить замечания. Плюсом можно быстро заходить на детальный экран контакта и выходить - случится крэш. Его надо поправить

2021-04-07 06:22 UTC, thealbre commented on app/src/main/java/com/classic117/classicproject/ContactDetailsFragment.kt
> +const val ARG_PERSON_ID = "id"
nit*: вынести в константы отельным файлом и объектом

*Сокращение от "Придирка". Т.е. не обязательно, но желательное к исправлению https://stackoverflow.com/questions/27810522/what-does-nit-mean-in-hacker-speak

2021-04-07 06:22 UTC, thealbre commented on app/src/main/java/com/classic117/classicproject/BirthdayReceiver.kt
> +            set(DAY_OF_MONTH, 29)
Использовать константу как в FEBRUARY29 в классе ContactDetailsFragment.kt

2021-04-07 06:22 UTC, thealbre commented on app/src/main/java/com/classic117/classicproject/ContactDetailsFragment.kt
>              setTitle(R.string.contact_details_bar)
оставить в блоке (activity as AppCompatActivity?)?.supportActionBar?.apply { только setTitle, остальное, что не относится к supportActionBar - вынести просто после }

2021-04-07 06:22 UTC, thealbre commented on app/src/main/java/com/classic117/classicproject/ContactDetailsFragment.kt
> +    private lateinit var button: Button
не исправлено

2021-04-07 06:22 UTC, thealbre commented on app/src/main/java/com/classic117/classicproject/ContactDetailsFragment.kt
> +            Log.d(TAG, "AlarmOn status in before click $alarmOn")
nit: логи для тестирования работоспобности всё же лучше убирать. Для тестового норм, но большое кол-во записей в Log увеличивает кол-во строчек и усложняет чтение кода

2021-04-07 06:22 UTC, thealbre commented on app/src/main/java/com/classic117/classicproject/ContactDetailsFragment.kt
> +                nextAlarmDate().get(Calendar.DAY_OF_MONTH),
nextAlarmDate() в отдельную переменную, т.е. получать значение из функции только один раз

2021-04-07 06:22 UTC, thealbre commented on app/src/main/java/com/classic117/classicproject/ContactDetailsFragment.kt
> +    private fun nextAlarmDate(): Calendar {
1. надо вынести всю логику, работу с Calendar в отдельный класс
2. надо выделить часть с проверкой `is29February и isLeap` и установкой `set(DAY_OF_MONTH, 29) и set(Calendar.MONTH, 1)` в отдельную функцию

2021-04-07 06:22 UTC, thealbre commented on app/src/main/java/com/classic117/classicproject/ContactDetailsFragment.kt
> +        if (birthdayDate?.before(today)!!) {
убрать null exception `!!`

2021-04-07 06:22 UTC, thealbre commented on app/src/main/java/com/classic117/classicproject/Person.kt
> +    var birthday: Calendar,
nit: сделать все поля nullable, тогда будет проще с ними работать. Если null - значит данных нет.

2021-04-07 06:22 UTC, thealbre commented on app/src/main/res/layout/contact_details_fragment.xml
> +        app:layout_constraintHorizontal_bias="0.498"
nit: 0.5

2021-04-07 06:22 UTC, thealbre commented on app/src/main/res/layout/contact_details_fragment.xml
> +        android:layout_width="@dimen/mConstrain"
лучше вернуть 0dp сюда, чтобы не лезть в dimen и смотреть что там за значение прячется под `mConstrain`
Для 0dp это исключение, т.к. это такая же основная "настройка" для contraint как и match_parent

2021-04-07 17:09 UTC, Vershinin-V-V commented on app/src/main/java/com/classic117/classicproject/BirthdayReceiver.kt
> +    private var contactName: String = ""
Эта переменная мне еще в showNotification() нужна.
Остальное всё исправил

2021-04-08 10:06 UTC, thealbre commented on app/src/main/java/com/classic117/classicproject/ContactDetailsFragment.kt
> +        contactId = arguments?.getInt(ARG_PERSON_ID)
nit: contactId = requireArguments.getInt(ARG_PERSON_ID)

2021-04-08 10:06 UTC, thealbre commented on app/src/main/java/com/classic117/classicproject/BirthdayReceiver.kt
> +        alarmMgr.set(AlarmManager.RTC_WAKEUP, CalendarUtil().nextAlarmDate(getInstance()).timeInMillis, pendingIntent)
такие длинные строчки лучше стараться делать короче, например перенести на разные строки аргументы
```
        alarmMgr.set(
            AlarmManager.RTC_WAKEUP,
            CalendarUtil.nextAlarmDate(getInstance()).timeInMillis,
            pendingIntent
        )
```

2021-04-08 10:06 UTC, thealbre commented on app/src/main/java/com/classic117/classicproject/BirthdayReceiver.kt
> +        alarmMgr.set(AlarmManager.RTC_WAKEUP, CalendarUtil().nextAlarmDate(getInstance()).timeInMillis, pendingIntent)
Это быстро можно сделать, поставив курсор(каретку) после открывающей скобкой `(` и нажав Alt+Enter. Тут нужен put arguments on separate lines
![image](https://user-images.githubusercontent.com/27574322/114008234-17081a00-9873-11eb-9c66-21ac3fc6004a.png)

2021-04-08 10:06 UTC, thealbre commented on app/src/main/java/com/classic117/classicproject/BirthdayReceiver.kt
> +        alarmMgr.set(AlarmManager.RTC_WAKEUP, CalendarUtil().nextAlarmDate(getInstance()).timeInMillis, pendingIntent)
Непонятен чей getInstance(). лучше заменить на `Calendar.getInstance()` и `import java.util.Calendar`

2021-04-08 13:53 UTC, Vershinin-V-V commented on app/src/main/java/com/classic117/classicproject/BirthdayReceiver.kt
> +        alarmMgr.set(AlarmManager.RTC_WAKEUP, CalendarUtil().nextAlarmDate(getInstance()).timeInMillis, pendingIntent)
это ide так сократила, ей так, видимо, понятней).

Все поправил

2021-04-10 12:46 UTC, thealbre reviewed
Вроде всё чётко, осталось только починить эти комментарии и можно будет вливать в основную main ветку)

2021-04-10 12:46 UTC, thealbre commented on app/src/main/java/com/classic117/classicproject/MainActivity.kt
> +        if (fragmentManager.backStackEntryCount == 1) {
nit, тут логика непонятна, лучше тогда сделать >1, если это для того, чтобы сбрасывать весь Stack фрагментов до корневого

2021-04-10 12:46 UTC, thealbre commented on app/src/main/java/com/classic117/classicproject/BirthdayReceiver.kt
> +        val builder = NotificationCompat.Builder(context, CONTACT_NAME)
CONTACT_NAME -> CHANNEL_ID
если это не сделать, то нотификации не будут приходить, т.к. регистрируется NotificationChannel именно этой перменной CHANNEL_ID

2021-04-11 16:45 UTC, Vershinin-V-V commented on app/src/main/java/com/classic117/classicproject/MainActivity.kt
> +        if (fragmentManager.backStackEntryCount == 1) {
На данном этапе, все равно, в стеке либо 0 либо 1)

2021-04-11 16:49 UTC, Vershinin-V-V commented on app/src/main/java/com/classic117/classicproject/MainActivity.kt
> +                .add(R.id.fragment_container, ContactListFragment())
По предыдущему коменту убрал повторяющийся код в отдельную функцию, а здесь немного не понял что не так и что исправить

2021-04-12 05:28 UTC, thealbre commented on app/src/main/java/com/classic117/classicproject/MainActivity.kt
> +        if (fragmentManager.backStackEntryCount == 1) {
Но если появится ещё один фрагмент, например детальный просмотр фотографии, или редактирование профиля - то это уже не будет работать и придётся править баг)

2021-04-12 05:34 UTC, thealbre commented on app/src/main/java/com/classic117/classicproject/MainActivity.kt
> +                .add(R.id.fragment_container, ContactListFragment())
Нужно заменить ContactListFragment() на ContactListFragment.newInstance() и следовательно добавить в companion object у ContactListFragment метод newInstance:
```
    companion object {
        fun newInstance() = ContactListFragment()
    }
```

Это делается для того, чтобы код создания фрагментов был однотипным, чтобы в будущем, при появлении у фрагмента аргументов не пришлось бы переписать код, добавлять companion object, писать newInstance, заменять `***()` на `****.newInstance(arg)`. Единый стиль вообщем)

2021-04-12 06:45 UTC, Vershinin-V-V commented on app/src/main/java/com/classic117/classicproject/MainActivity.kt
> +        if (fragmentManager.backStackEntryCount == 1) {
"дом Винчестеров" сейчас здесь обои доклею, затем под них трубы и электрику(contactResolver) проведу. Ну а потом и фундаментом можно заняться)))

2021-04-12 07:05 UTC, thealbre commented
Всё отлично, можно приступать к следующему ДЗ)

2021-04-12 07:05 UTC, merged